<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%><!DOCTYPE HTML><html lang="zh-CN"><head>    <script>        var _hmt = _hmt || [];        (function() {            var hm = document.createElement("script");            hm.src = "https://hm.baidu.com/hm.js?14a62041b4de52f2586d283b14d1175c";            var s = document.getElementsByTagName("script")[0];            s.parentNode.insertBefore(hm, s);        })();    </script>	<meta charset="UTF-8">	<meta name="description" content="444" />	<title>333</title>	<link rel="stylesheet" type="text/css" href="/html/weixinSell/css/marketing.css" />	<script type="text/javascript" src="/html/js/jquery-1.10.2.js"></script>	<script type="text/javascript" src="/js/webSite.js"></script>	<style>		.video-box{			position: fixed;			top:50%;			left: 50%;			width:100%;			height: 100%;			z-index: 90;			margin-left: -400px;			margin-top: -250px;			display: none;		}		.video-close{			position: absolute;			left: 740px;			color: #fff;			top: 40px;			z-index: 99;			cursor: pointer;		}	</style></head><body style="background: #f8f8f8;"><%@include file="/html/common/clearfix.jsp"%><div class="a-details">	<div class="a-details-l">		<ul class="a-details-l-box">			<li>  <h3>中新网北京10月14日</h3> <p>中新网北京10月14日电根据气象预报，今年第20号台风“卡努”将于15日晚上到16日凌晨在海南三亚到广东湛江一带沿海登陆。受台风影响，13日夜间起，浙江沿海、福建沿海、台湾南部和西部沿海、广东沿海、海南东部沿海将有7-8级大风。台风登陆前后，海南沿海可能出现巨浪到狂浪区，14日10时起，琼州海峡将全线停航。</p><img src="" class="a-details-img" onclick="productOpenVideo00();" ><div class="video-box" id="product-video-box00">
    <span class="video-close" onclick="productCloseVideo00()">关闭</span>
    <video preload="none" controls width="800" height="500" id="product-videoMedia00" style="background-color: #000">
        <source src="" type="video/mp4">
    </video>
</div>
<script>
    var productCloseVideo00 =function(){
        var media = document.getElementById("product-videoMedia00");
        media.pause();
        $('#product-video-box00').hide();
    }
    var productOpenVideo00 = function(){
        var media = document.getElementById("product-videoMedia00");
        media.play();
        $('#product-video-box00').show();
    }
</script></li><li>  <h3>——广东、海南东部沿海将有8级大风</h3> <p>根据中央气象台13日晚间发布的预报<br>今年第20号台风“卡努”(热带风暴级)的中心<br>13日下午5点位于海南万宁市偏东方向约<br>930公里的南海东部海面上。预计，“卡努”<br>将以每小时10-15公里的速度向西偏北方<br>向移动，逐渐向海南岛东部和广东西部一<br>带沿海靠近，强度逐渐加强，最强可达<br>强热带风暴级或台风级(11-13级，30-38米/秒)<br></p></li>		</ul>	</div>	<div class="a-details-r">		<div class="a-details-r-t">			<div class="a-details-unified">				<div class="a-details-unified-l">					<img src="http://maint.duofriend.com/upload/image/websiteUpload/website/D15EFF6CEA9643B2E08B3C6232EBD3E7.jpg" style="width: 50px;height:50px;">				</div>				<div class="a-details-unified-r">					<h4>111<a href="/html/instructions.jsp">(使用手册)</a></h4>					<p>222</p>				</div>			</div>		</div>		<div class="a-details-r-b">			<div class="a-details-r-t-title">				<p>相关推荐</p>			</div>			<div class="a-details-r-roll">			</div>		</div>	</div></div><script>    $(function () {        var productJson = WSFUNCTION.doPost(            "/productCenterNew/html/productlist", {});        var products = productJson.products;        var  a = 15;        if (a > products.length){            a = products.length;		}        for(var i=0;i<a;i++){            $('.a-details-r-roll').append('	<div class="a-details-unified">'                +'<div class="a-details-unified-l">'                +'<a href="productNew_'+products[i].id+'.jsp " ><img src="'+products[i].logourl+'"  style="width: 50px;height: 50px;">'                +'</div>'                +'<div class="a-details-unified-r">'                +' <h4>' +products[i].pcname+'</h4>'                +'<p>'+products[i].pcdesc+'</p>'                +' </a></div>'                +' </div>');        }    })</script><%@include file="/html/common/footer.jsp"%></body></html>