package com.gt.model;

// Generated 2016-1-12 11:31:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TManEmployeeAssess generated by hbm2java
 */
@Entity
@Table(name = "t_man_employee_assess")
public class TManEmployeeAssess implements java.io.Serializable {

	private Integer id;
	private Integer employeeid;
	private Integer groomingnum;
	private String groomingtext;
	private Integer expressnum;
	private String expresstext;
	private Integer servicenum;
	private String servicetext;
	private String propose;
	private String createTime;
	private Integer majornum;
	private String majortext;

	public TManEmployeeAssess() {
	}

	public TManEmployeeAssess(Integer employeeid, Integer groomingnum,
			String groomingtext, Integer expressnum, String expresstext,
			Integer servicenum, String servicetext, String propose,
			String createTime,Integer majornum,String majortext) {
		this.employeeid = employeeid;
		this.groomingnum = groomingnum;
		this.groomingtext = groomingtext;
		this.expressnum = expressnum;
		this.expresstext = expresstext;
		this.servicenum = servicenum;
		this.servicetext = servicetext;
		this.propose = propose;
		this.createTime = createTime;
		this.majornum = majornum;
		this.majortext = majortext;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "employeeid")
	public Integer getEmployeeid() {
		return this.employeeid;
	}

	public void setEmployeeid(Integer employeeid) {
		this.employeeid = employeeid;
	}

	@Column(name = "groomingnum")
	public Integer getGroomingnum() {
		return this.groomingnum;
	}

	public void setGroomingnum(Integer groomingnum) {
		this.groomingnum = groomingnum;
	}

	@Column(name = "groomingtext", length = 200)
	public String getGroomingtext() {
		return this.groomingtext;
	}

	public void setGroomingtext(String groomingtext) {
		this.groomingtext = groomingtext;
	}

	@Column(name = "expressnum")
	public Integer getExpressnum() {
		return this.expressnum;
	}

	public void setExpressnum(Integer expressnum) {
		this.expressnum = expressnum;
	}

	@Column(name = "expresstext", length = 200)
	public String getExpresstext() {
		return this.expresstext;
	}

	public void setExpresstext(String expresstext) {
		this.expresstext = expresstext;
	}

	@Column(name = "servicenum")
	public Integer getServicenum() {
		return this.servicenum;
	}

	public void setServicenum(Integer servicenum) {
		this.servicenum = servicenum;
	}

	@Column(name = "servicetext", length = 200)
	public String getServicetext() {
		return this.servicetext;
	}

	public void setServicetext(String servicetext) {
		this.servicetext = servicetext;
	}

	@Column(name = "propose", length = 200)
	public String getPropose() {
		return this.propose;
	}

	public void setPropose(String propose) {
		this.propose = propose;
	}

	@Column(name = "create_time", length = 20)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public Integer getMajornum() {
		return majornum;
	}

	public void setMajornum(Integer majornum) {
		this.majornum = majornum;
	}

	public String getMajortext() {
		return majortext;
	}

	public void setMajortext(String majortext) {
		this.majortext = majortext;
	}

}
